### ISSUE TITLE
Successful payment notification

### ISSUE THREAD

**Issue by burzum** [ismailasci/omnipay-sofort#3]
I think it might be right that you don't get the status immediatelly after doing the payment but the API uses notifications to inform your app about changes to your payments, similar to Paypals IPN or Authorize.nets "silent post".

The problem is, I haven't yet figured out (I'm new to the Omnipay lib) how to deal with these notification callbacks in Omnipay. Before I started to switch to Omnipay I was working on my own lib, see here how I implemented the callback using the SDK.

https://github.com/burzum/Sofort/blob/develop/Lib/Payment/SofortUeberweisungProcessor.php#L95

There must be a way to get the status of the payment using Omnipay, I'm sure there is a way to listen to the callback notifications and then do something depending on the state of the payment. If not...oh my... I think I'll have to continue with my lib instead of Omnipay.

**Comment by ismailasci** [comment]
Hey there,

Thanks for the issue and sorry for the delay. I don't think what you suggested is in concern of Omnipay. Omnipay is just a payment provider, listening notification links etc. must be handled by your application's HTTP level.

**Comment by burzum** [comment]
Well, I disagree, almost all payment providers use callbacks, Authorize.net (Silent Post), Paypal (IPN) and Sofort as well. So this is in fact part of the adapter or Omnipay as it should abstract the notifications from the APIs as well.
